const DASHBOARD_HTML = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Mozzy Print Service</title>
  <style>
    :root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:#0b1120;color:#fff;font:14px system-ui,-apple-system,Segoe UI,sans-serif}.wrap{max-width:1050px;margin:auto;padding:24px}header{display:flex;justify-content:space-between;align-items:center;gap:16px;border-bottom:1px solid #293246;padding-bottom:18px}h1{margin:0;font-size:20px}.muted{color:#94a3b8;font-size:12px}.tabs{display:flex;gap:8px;margin:20px 0}.tabs button,.button{border:1px solid #334155;border-radius:8px;background:#172033;color:#fff;padding:9px 13px;cursor:pointer}.tabs button.active,.button.primary{background:#4f46e5;border-color:#6366f1}.panel{display:none}.panel.active{display:block}.card{background:#111827;border:1px solid #293246;border-radius:12px;padding:18px;margin-bottom:14px}.toolbar{display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap}.input{width:100%;background:#0b1120;border:1px solid #334155;color:#fff;border-radius:7px;padding:9px}.feed{max-height:620px;overflow:auto;margin-top:14px}.log{display:flex;gap:11px;align-items:flex-start;padding:11px;border:1px solid #273246;border-radius:9px;background:#0b1120;margin-bottom:8px}.dot{width:10px;height:10px;border-radius:50%;margin-top:5px;flex:none}.green{background:#4ade80}.red{background:#fb7185}.yellow{background:#facc15}.blue{background:#38bdf8}.purple{background:#a78bfa}.title{font-weight:700;color:#fff}.message{font-size:13px;color:#fff;margin-top:3px}.time{font-size:11px;color:#94a3b8;margin-top:5px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:13px}.full{grid-column:1/-1}label{font-size:12px;color:#cbd5e1;display:block;margin-bottom:5px}.area{display:grid;grid-template-columns:1fr 1.5fr 100px auto;gap:10px;align-items:end;padding:12px;border:1px solid #293246;border-radius:9px;margin-top:10px}.remove{background:#3f1720;color:#fff;border:1px solid #7f1d1d;border-radius:7px;padding:9px;cursor:pointer}.notice{color:#fbbf24;min-height:20px;margin-top:12px}@media(max-width:700px){.grid,.area{grid-template-columns:1fr}.full{grid-column:auto}}
  </style>
</head>
<body><div class="wrap">
  <header><div><h1>🖨️ Mozzy Print Service</h1><div class="muted">Local printer settings and activity</div></div><button class="button" onclick="refreshAll()">Refresh</button></header>
  <nav class="tabs"><button class="active" data-tab="logs" onclick="tab('logs')">Activity</button><button data-tab="settings" onclick="tab('settings')">Printer Settings</button><button data-tab="test" onclick="tab('test')">Test Print</button></nav>
  <section id="logs" class="panel active"><div class="card"><div class="toolbar"><div><strong>Service activity</strong><div class="muted">Simple status messages from this print service</div></div><input id="search" class="input" style="max-width:300px" placeholder="Search activity" oninput="renderLogs()"></div><div id="feed" class="feed"><div class="muted">Loading activity...</div></div></div></section>
  <section id="settings" class="panel"><form onsubmit="save(event)"><div class="card"><strong>Connection and format</strong><div class="grid" style="margin-top:14px"><div><label>POS server URL</label><input id="server" required class="input"></div><div><label>API key</label><input id="key" required class="input"></div><div><label>Paper width</label><select id="width" class="input"><option value="33">33 characters (75mm paper)</option><option value="35">35 characters (75mm paper)</option><option value="40">40 characters (80mm paper)</option><option value="42">42 characters</option><option value="48">48 characters</option></select></div><div><label>Default copies</label><input id="copies" type="number" min="1" max="10" class="input"></div></div></div><div class="card"><strong>Print areas</strong><div class="muted">Add an area, type the exact Windows printer name, and choose copies.</div><div id="areas"></div><button type="button" class="button" style="margin-top:12px" onclick="addArea()">＋ Add print area</button></div><button class="button primary" type="submit">Save settings</button><div id="notice" class="notice"></div></form></section>
  <section id="test" class="panel"><div class="card"><strong>Test print</strong><div class="muted" style="margin:6px 0 14px">Choose a configured area to send a test ticket.</div><div id="tests"></div></div></section>
</div><script>
let logs=[],config={};
function tab(id){document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelector('[data-tab="'+id+'"]').classList.add('active')}
function summary(log){const m=String(log.message||''),l=m.toLowerCase(),name=m.split('"')[1]||'the selected printer',job=(m.match(/Job #([0-9]+)/i)||[])[1];if(l.includes('connected to pos server')||l.includes('registration successful'))return['Server connected','Connected to the POS server successfully.','green'];if(l.includes('connection failed')||l.includes('disconnected from pos')||l.includes('xhr poll'))return['Server connection','Cannot connect to the POS server. Check the network and server address.','red'];if(l.includes('connecting to pos'))return['Server connection','Connecting to the POS server...','yellow'];if(l.includes('offline')||l.includes('failed to open printer')||l.includes('printer not available')||l.includes('raw print failed'))return['Printer connection','Cannot reach '+name+'. Check its power, Windows driver, and name.','red'];if(l.includes('printed ')||l.includes('printed successfully'))return['Printing complete','Sent '+(job?'job #'+job+' ':'')+'to '+name+'.','green'];if(l.includes('received job')||l.includes('printing copy'))return['Printing','Printing '+(job?'job #'+job+'.':'a new job.') ,'blue'];if(l.includes('configuration updated'))return['Settings saved','Your printer settings have been applied.','purple'];return[log.type==='error'?'Service error':'Print service',m||'Service activity updated.',log.type==='error'?'red':log.type==='warn'?'yellow':'blue']}
function renderLogs(){const feed=document.getElementById('feed'),q=document.getElementById('search').value.toLowerCase();feed.innerHTML='';logs.filter(log=>{const s=summary(log);return !q||(s[0]+' '+s[1]).toLowerCase().includes(q)}).slice(-150).reverse().forEach(log=>{const s=summary(log),row=document.createElement('div');row.className='log';row.innerHTML='<span class="dot '+s[2]+'"></span><div><div class="title"></div><div class="message"></div><div class="time"></div></div>';row.querySelector('.title').textContent=s[0];row.querySelector('.message').textContent=s[1];row.querySelector('.time').textContent=log.timestamp||'';feed.appendChild(row)});if(!feed.children.length)feed.innerHTML='<div class="muted">No matching activity yet.</div>'}
async function loadLogs(){try{const r=await fetch('/api/logs',{cache:'no-store'}),d=await r.json();if(d.success){logs=d.logs||[];renderLogs()}}catch{}}
function addArea(area='',printer='',copies=1){const row=document.createElement('div');row.className='area';row.innerHTML='<div><label>Area</label><input required class="input area-name" placeholder="cashier" value=""></div><div><label>Windows printer name</label><input required class="input area-printer" placeholder="EPSON80" value=""></div><div><label>Copies</label><input required class="input area-copies" type="number" min="1" max="10" value="1"></div><button type="button" class="remove">Remove</button>';row.querySelector('.area-name').value=area;row.querySelector('.area-printer').value=printer;row.querySelector('.area-copies').value=copies;row.querySelector('.remove').onclick=()=>row.remove();document.getElementById('areas').appendChild(row)}
function fill(c){config=c;server.value=c.SERVER_URL||'';key.value=c.API_KEY||'';width.value=c.PAPER_WIDTH||40;copies.value=c.PRINT_COPIES||1;areas.innerHTML='';const map=c.PRINTER_MAP||{},cm=c.PRINT_COPIES_MAP||{};(c.PRINT_AREAS||Object.keys(map)).forEach(a=>addArea(a,map[a]||'',cm[a]||1));renderTests()}
function renderTests(){tests.innerHTML='';(config.PRINT_AREAS||[]).forEach(a=>{const b=document.createElement('button');b.className='button';b.style.marginRight='8px';b.textContent='Test '+a;b.onclick=()=>testPrint(a);tests.appendChild(b)})}
async function loadConfig(){try{const r=await fetch('/api/config'),d=await r.json();if(d.success)fill(d.config)}catch{notice.textContent='Cannot load settings.'}}
async function save(e){e.preventDefault();const list=[...document.querySelectorAll('.area')],PRINT_AREAS=[],PRINTER_MAP={},PRINT_COPIES_MAP={};for(const row of list){const a=row.querySelector('.area-name').value.trim().toLowerCase().replace(/\\s+/g,'_'),p=row.querySelector('.area-printer').value.trim();if(!a||!p){notice.textContent='Every area needs a name and printer.';return}if(PRINT_AREAS.includes(a)){notice.textContent='Area names must be unique.';return}PRINT_AREAS.push(a);PRINTER_MAP[a]=p;PRINT_COPIES_MAP[a]=Number(row.querySelector('.area-copies').value)||1}const payload={...config,SERVER_URL:server.value.trim(),API_KEY:key.value.trim(),PAPER_WIDTH:Number(width.value),PRINT_COPIES:Number(copies.value)||1,PRINT_AREAS,PRINTER_MAP,PRINT_COPIES_MAP};const r=await fetch('/api/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),d=await r.json();notice.textContent=d.success?'Settings saved.':'Save failed: '+(d.message||'Unknown error');if(d.success){fill(payload);loadLogs()}}
async function testPrint(area){const r=await fetch('/api/test-print',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({printArea:area})}),d=await r.json();alert(d.success?'Test print sent.':'Test failed: '+d.message);loadLogs()}
function refreshAll(){loadConfig();loadLogs()}loadConfig();loadLogs();setInterval(loadLogs,2000);
</script></body></html>`;
module.exports = DASHBOARD_HTML;
